// Conservative textual guard for Cypher generated by an LLM (reportAI).
//
// A system prompt is not a security boundary: the model (or an indirect prompt
// injection carried by ticket titles in tool results) can emit any query. Before
// execution we therefore require, textually and conservatively:
//
//   1. no write / admin / procedure clauses (CREATE, MERGE, SET, DELETE, CALL db.*,
//      apoc.* outside a small pure-function allowlist, LOAD CSV, dbms.*, ...);
//   2. no string-escaping tricks (backslashes, backticks, `;`, comments are stripped);
//   3. the only parameter is $tenantId;
//   4. EVERY path pattern is anchored to the tenant: at least one node of the path
//      carries `{tenant_id: $tenantId}` inline, or `alias.tenant_id = $tenantId`
//      in a WHERE (accepted only when the query has no OR/XOR/NOT that could
//      neutralise it), or re-uses an alias already bound by an anchored path.
//
//   5. what the tenant's graph holds but a report must never read (revisione
//      totale · D-1): every node pattern names its labels (or re-uses an alias
//      that does), no label is one of SENSITIVE_LABELS, no `!`/`%` label
//      expression, no access to a SENSITIVE_PROPERTY_KEYS property and no dynamic
//      `x['…']` access. Before, an operator with `report.ai` (or a prompt
//      injection in a ticket title) could read OutboundWebhook.secret/headers,
//      Slack webhook URLs and transform scripts through the tool.
//      `redactSensitiveValue` is the second line on the rows the query returns.
//
// The check is deliberately strict: a legitimate query it rejects costs the
// model one retry; a malicious query it accepts costs a cross-tenant leak.

export class UnsafeCypherError extends Error {
  readonly code = 'UNSAFE_CYPHER'
  constructor(message: string) {
    super(`Query rejected by the security guard: ${message}`)
    this.name = 'UnsafeCypherError'
  }
}

export const MAX_CYPHER_LENGTH = 4000

/** Nodes holding integration secrets, credentials or configuration code: never readable by a report. */
export const SENSITIVE_LABELS: ReadonlySet<string> = new Set([
  'OutboundWebhook', 'InboundWebhook', 'ApiKey', 'NotificationChannel', 'SlackInstallation',
  'SyncSource', 'SyncConflict', 'SyncChangeRecord', 'MigrationLock', 'Migration', 'LoginProvider',
])

/** Property names that hold secrets on any node. */
export const SENSITIVE_PROPERTY_KEYS: ReadonlySet<string> = new Set([
  'secret', 'headers', 'key_hash', 'key_prefix', 'webhook_url', 'transform_script', 'token', 'password',
  'credentials', 'encrypted_credentials', 'signing_secret', 'signing_secret_enc', 'bot_token', 'bot_token_enc',
  'client_secret', 'embedding',
])

const WRITE_KEYWORD_RE = /(?<![\w.$])(CREATE|MERGE|SET|DELETE|DETACH|REMOVE|DROP|FOREACH|LOAD|USING|ALTER|GRANT|DENY|REVOKE|START|STOP|TERMINATE|INSTALL|IMPORT|EXPORT|SHOW|USE|ENABLE|RENAME|DEALLOCATE|ASSIGN|PERIODIC|COMMIT)(?!\w)/i
const CALL_RE          = /(?<![\w.])CALL(?!\w)\s*([^\s]*)/gi
const SAFE_PROC_RE     = /^apoc\.(text|coll|map|date)\.[A-Za-z0-9_.]+/
const DB_NAMESPACE_RE  = /(?<![\w.])(dbms|db)\./i
const APOC_RE          = /(?<![\w.])apoc\.(?!(text|coll|map|date)\.)/i
const AUTH_RE          = /:auth/i
const PARAM_RE         = /\$([A-Za-z_][A-Za-z0-9_]*)/g
const INLINE_WHERE_RE  = /\(\s*[A-Za-z_]?\w*\s*:\s*\w+[^()]*(?<!\w)WHERE(?!\w)/i

// (alias?)(:Label(:|&|| Label)*)?({inline map})?
const NODE_RE = /\(\s*([A-Za-z_][A-Za-z0-9_]*)?\s*((?::\s*[A-Za-z_][A-Za-z0-9_]*(?:\s*[:|&!]\s*[A-Za-z_][A-Za-z0-9_]*)*)?)\s*(\{[^{}]*\})?\s*\)/g
const INLINE_TENANT_RE = /(?<!\w)tenant_id\s*:\s*\$tenantId(?!\w)/
const WHERE_TENANT_RE  = /(?<![\w.])([A-Za-z_][A-Za-z0-9_]*)\.tenant_id\s*=\s*\$tenantId(?!\w)|\$tenantId\s*=\s*(?<![\w.])([A-Za-z_][A-Za-z0-9_]*)\.tenant_id(?!\w)/g
const BOOLEAN_NEUTRALISER_RE = /(?<![\w.])(OR|XOR|NOT)(?!\w)/i
const IS_NOT_RE = /(?<![\w.])IS\s+NOT(?!\w)/gi

const SENSITIVE_PROPERTY_RE = new RegExp(`(?<![\\w$])[A-Za-z_][A-Za-z0-9_]*\\s*\\.\\s*(${[...SENSITIVE_PROPERTY_KEYS].join('|')})(?!\\w)|\\{[^}]*(?<![\\w$])(${[...SENSITIVE_PROPERTY_KEYS].join('|')})\\s*:`, 'i')
const DYNAMIC_PROPERTY_RE = /[A-Za-z0-9_)\]]\s*\[\s*(''|""|\$)/

/**
 * Seconda linea di D-1 sulle righe restituite: un nodo con un'etichetta
 * sensibile diventa `"[redacted]"`, una chiave sensibile di una mappa o di un
 * nodo sparisce. Ricorsiva su liste e mappe; i valori primitivi passano.
 */
export function redactSensitiveValue(value: unknown): unknown {
  if (value === null || typeof value !== 'object') return value
  if (Array.isArray(value)) return value.map(redactSensitiveValue)
  const v = value as Record<string, unknown>
  if (Array.isArray(v['labels']) && typeof v['properties'] === 'object' && v['properties'] !== null) {
    if ((v['labels'] as unknown[]).some((l) => typeof l === 'string' && SENSITIVE_LABELS.has(l))) return '[redacted]'
    return { ...v, properties: redactSensitiveValue(v['properties']) }
  }
  if ('toNumber' in v && typeof v['toNumber'] === 'function') return value
  const out: Record<string, unknown> = {}
  for (const [k, inner] of Object.entries(v)) {
    if (SENSITIVE_PROPERTY_KEYS.has(k.toLowerCase())) continue
    out[k] = redactSensitiveValue(inner)
  }
  return out
}

/** Words after which a `(` opens a pattern, not a function call. */
const PATTERN_KEYWORDS = new Set([
  'MATCH', 'WHERE', 'WITH', 'RETURN', 'AND', 'OR', 'XOR', 'NOT', 'UNWIND',
  'EXISTS', 'ALL', 'ANY', 'NONE', 'SINGLE', 'WHEN', 'THEN', 'ELSE', 'CASE',
  'END', 'IN', 'IS', 'OPTIONAL', 'CALL', 'YIELD', 'ON', 'STARTS', 'ENDS', 'CONTAINS',
  'UNION', 'DISTINCT', 'AS', 'BY', 'SKIP', 'LIMIT', 'ASC', 'DESC',
])

/**
 * Returns the query with string literal contents blanked ('' / "") and
 * comments removed. Throws on constructs that make textual analysis unreliable.
 */
export function stripCypherLiterals(query: string): string {
  let out = ''
  let i = 0
  while (i < query.length) {
    const ch = query[i]!
    if (ch === "'" || ch === '"') {
      let j = i + 1
      let closed = false
      while (j < query.length) {
        if (query[j] === '\\') { j += 2; continue }
        if (query[j] === ch) { closed = true; break }
        j++
      }
      if (!closed) throw new UnsafeCypherError('unterminated string literal')
      out += ch + ch
      i = j + 1
      continue
    }
    if (ch === '/' && query[i + 1] === '/') {
      const nl = query.indexOf('\n', i)
      i = nl === -1 ? query.length : nl
      continue
    }
    if (ch === '/' && query[i + 1] === '*') {
      const end = query.indexOf('*/', i + 2)
      if (end === -1) throw new UnsafeCypherError('unterminated comment')
      out += ' '
      i = end + 2
      continue
    }
    if (ch === '\\') throw new UnsafeCypherError('backslash outside a string')
    if (ch === '`') throw new UnsafeCypherError('backtick identifiers are not allowed')
    if (ch === ';') throw new UnsafeCypherError('one statement per query (";" is not allowed)')
    out += ch
    i++
  }
  return out
}

function precedingToken(text: string, index: number): { word: string | null; char: string | null } {
  let k = index - 1
  while (k >= 0 && /\s/.test(text[k]!)) k--
  if (k < 0) return { word: null, char: null }
  const char = text[k]!
  if (!/[\w$]/.test(char)) return { word: null, char }
  let start = k
  while (start >= 0 && /[\w$]/.test(text[start]!)) start--
  return { word: text.slice(start + 1, k + 1), char }
}

interface NodePattern {
  alias:        string | null
  hasLabel:     boolean
  labels:       string[]
  labelExpr:    string
  inlineTenant: boolean
  continues:    boolean   // preceded by `-` / `>` → same path as previous node
}

function extractNodePatterns(text: string): NodePattern[] {
  const nodes: NodePattern[] = []
  NODE_RE.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = NODE_RE.exec(text)) !== null) {
    const { word, char } = precedingToken(text, m.index)
    if (word !== null && !PATTERN_KEYWORDS.has(word.toUpperCase())) {
      // identifier( … ) → function call such as count(n), skip
      continue
    }
    nodes.push({
      alias:        m[1] ?? null,
      hasLabel:     (m[2] ?? '').length > 0,
      labels:       (m[2] ?? '').split(/[:|&!%\s]+/).filter(Boolean),
      labelExpr:    m[2] ?? '',
      inlineTenant: m[3] ? INLINE_TENANT_RE.test(m[3]) : false,
      continues:    char === '-' || char === '>',
    })
  }
  return nodes
}

/**
 * Throws UnsafeCypherError unless `query` is a read-only, tenant-anchored
 * Cypher statement. Never mutates or executes anything.
 */
export function assertSafeReadOnlyCypher(query: string): void {
  if (typeof query !== 'string' || !query.trim()) throw new UnsafeCypherError('empty query')
  if (query.length > MAX_CYPHER_LENGTH) throw new UnsafeCypherError(`query too long (> ${MAX_CYPHER_LENGTH} characters)`)

  const text = stripCypherLiterals(query)

  const write = WRITE_KEYWORD_RE.exec(text)
  if (write) throw new UnsafeCypherError(`clause not allowed: ${write[1]!.toUpperCase()} (only reads are allowed)`)
  if (DB_NAMESPACE_RE.test(text)) throw new UnsafeCypherError('db.* and dbms.* procedures/functions are not allowed')
  if (APOC_RE.test(text)) throw new UnsafeCypherError('apoc.* is not allowed (except apoc.text/coll/map/date)')
  if (AUTH_RE.test(text)) throw new UnsafeCypherError('":auth" is not allowed')
  if (INLINE_WHERE_RE.test(text)) throw new UnsafeCypherError('WHERE inside a node pattern is not supported: use {tenant_id: $tenantId}')

  CALL_RE.lastIndex = 0
  let call: RegExpExecArray | null
  while ((call = CALL_RE.exec(text)) !== null) {
    const target = call[1] ?? ''
    if (target.startsWith('{')) continue                 // CALL { subquery }
    if (SAFE_PROC_RE.test(target)) continue
    throw new UnsafeCypherError(`CALL ${target || '<procedure>'} is not allowed`)
  }

  PARAM_RE.lastIndex = 0
  let param: RegExpExecArray | null
  while ((param = PARAM_RE.exec(text)) !== null) {
    if (param[1] !== 'tenantId') throw new UnsafeCypherError(`parameter $${param[1]} is not available: the only parameter is $tenantId`)
  }

  // Aliases scoped via WHERE alias.tenant_id = $tenantId — only trusted when no
  // boolean operator could neutralise the predicate (… OR true, NOT (…)).
  const whereScoped = new Set<string>()
  WHERE_TENANT_RE.lastIndex = 0
  let ws: RegExpExecArray | null
  while ((ws = WHERE_TENANT_RE.exec(text)) !== null) whereScoped.add(ws[1] ?? ws[2]!)
  if (whereScoped.size > 0 && BOOLEAN_NEUTRALISER_RE.test(text.replace(IS_NOT_RE, 'IS_NOT'))) {
    throw new UnsafeCypherError('with OR/XOR/NOT in the query the tenant constraint must be inline in the pattern: (x:Label {tenant_id: $tenantId})')
  }

  const nodes = extractNodePatterns(text)
  if (nodes.length === 0) throw new UnsafeCypherError('no node pattern found: every query must start from MATCH (x:Label {tenant_id: $tenantId})')

  // Group into paths and require each one to be anchored.
  const paths: NodePattern[][] = []
  for (const n of nodes) {
    if (n.continues && paths.length) paths[paths.length - 1]!.push(n)
    else paths.push([n])
  }

  const bound = new Set<string>()
  for (const path of paths) {
    const anchored = path.some(n =>
      n.inlineTenant ||
      (n.alias !== null && (whereScoped.has(n.alias) || bound.has(n.alias))),
    )
    if (!anchored) {
      const first = path[0]!
      const desc = first.alias ?? (first.hasLabel ? '<no alias>' : '()')
      throw new UnsafeCypherError(`pattern not bound to the tenant starting from (${desc}): add {tenant_id: $tenantId} to the node or ${first.alias ?? 'x'}.tenant_id = $tenantId`)
    }
    for (const n of path) if (n.alias) bound.add(n.alias)
  }

  // 5. What a report must never read (D-1).
  const labeledAliases = new Set(nodes.filter((n) => n.hasLabel && n.alias).map((n) => n.alias!))
  for (const n of nodes) {
    if (/[!%]/.test(n.labelExpr)) throw new UnsafeCypherError('label expressions with ! or % are not allowed: name the labels')
    const denied = n.labels.find((l) => SENSITIVE_LABELS.has(l))
    if (denied) throw new UnsafeCypherError(`label ${denied} is not readable by reports`)
    if (!n.hasLabel && !(n.alias && labeledAliases.has(n.alias))) {
      throw new UnsafeCypherError(`every node needs a label: (${n.alias ?? ''}) has none — write (${n.alias ?? 'x'}:Label)`)
    }
  }
  SENSITIVE_PROPERTY_RE.lastIndex = 0
  const prop = SENSITIVE_PROPERTY_RE.exec(text)
  if (prop) throw new UnsafeCypherError(`property ${prop[1]} is not readable by reports`)
  if (DYNAMIC_PROPERTY_RE.test(text)) throw new UnsafeCypherError('dynamic property access x[\'…\'] is not allowed: use x.property')

}
