// Conservative textual guard for Cypher generated by an LLM (reportAI).
//
// A system prompt is not a security boundary: the model (or an indirect prompt
// injection carried by ticket titles in tool results) can emit any query. Before
// execution we therefore require, textually and conservatively:
//
//   1. no write / admin / procedure clauses (CREATE, MERGE, SET, DELETE, CALL db.*,
//      apoc.* outside a small pure-function allowlist, LOAD CSV, dbms.*, ...);
//   2. no string-escaping tricks (backslashes, backticks, `;`, comments are stripped);
//   3. the only parameter is $tenantId;
//   4. EVERY path pattern is anchored to the tenant: at least one node of the path
//      carries `{tenant_id: $tenantId}` inline, or `alias.tenant_id = $tenantId`
//      in a WHERE (accepted only when the query has no OR/XOR/NOT that could
//      neutralise it), or re-uses an alias already bound by an anchored path.
//
// The check is deliberately strict: a legitimate query it rejects costs the
// model one retry; a malicious query it accepts costs a cross-tenant leak.

export class UnsafeCypherError extends Error {
  readonly code = 'UNSAFE_CYPHER'
  constructor(message: string) {
    super(`Query rifiutata dal guard di sicurezza: ${message}`)
    this.name = 'UnsafeCypherError'
  }
}

export const MAX_CYPHER_LENGTH = 4000

const WRITE_KEYWORD_RE = /(?<![\w.$])(CREATE|MERGE|SET|DELETE|DETACH|REMOVE|DROP|FOREACH|LOAD|USING|ALTER|GRANT|DENY|REVOKE|START|STOP|TERMINATE|INSTALL|IMPORT|EXPORT|SHOW|USE|ENABLE|RENAME|DEALLOCATE|ASSIGN|PERIODIC|COMMIT)(?!\w)/i
const CALL_RE          = /(?<![\w.])CALL(?!\w)\s*([^\s]*)/gi
const SAFE_PROC_RE     = /^apoc\.(text|coll|map|date)\.[A-Za-z0-9_.]+/
const DB_NAMESPACE_RE  = /(?<![\w.])(dbms|db)\./i
const APOC_RE          = /(?<![\w.])apoc\.(?!(text|coll|map|date)\.)/i
const AUTH_RE          = /:auth/i
const PARAM_RE         = /\$([A-Za-z_][A-Za-z0-9_]*)/g
const INLINE_WHERE_RE  = /\(\s*[A-Za-z_]?\w*\s*:\s*\w+[^()]*(?<!\w)WHERE(?!\w)/i

// (alias?)(:Label(:|&|| Label)*)?({inline map})?
const NODE_RE = /\(\s*([A-Za-z_][A-Za-z0-9_]*)?\s*((?::\s*[A-Za-z_][A-Za-z0-9_]*(?:\s*[:|&!]\s*[A-Za-z_][A-Za-z0-9_]*)*)?)\s*(\{[^{}]*\})?\s*\)/g
const INLINE_TENANT_RE = /(?<!\w)tenant_id\s*:\s*\$tenantId(?!\w)/
const WHERE_TENANT_RE  = /(?<![\w.])([A-Za-z_][A-Za-z0-9_]*)\.tenant_id\s*=\s*\$tenantId(?!\w)|\$tenantId\s*=\s*(?<![\w.])([A-Za-z_][A-Za-z0-9_]*)\.tenant_id(?!\w)/g
const BOOLEAN_NEUTRALISER_RE = /(?<![\w.])(OR|XOR|NOT)(?!\w)/i
const IS_NOT_RE = /(?<![\w.])IS\s+NOT(?!\w)/gi

/** Words after which a `(` opens a pattern, not a function call. */
const PATTERN_KEYWORDS = new Set([
  'MATCH', 'WHERE', 'WITH', 'RETURN', 'AND', 'OR', 'XOR', 'NOT', 'UNWIND',
  'EXISTS', 'ALL', 'ANY', 'NONE', 'SINGLE', 'WHEN', 'THEN', 'ELSE', 'CASE',
  'END', 'IN', 'IS', 'OPTIONAL', 'CALL', 'YIELD', 'ON', 'STARTS', 'ENDS', 'CONTAINS',
  'UNION', 'DISTINCT', 'AS', 'BY', 'SKIP', 'LIMIT', 'ASC', 'DESC',
])

/**
 * Returns the query with string literal contents blanked ('' / "") and
 * comments removed. Throws on constructs that make textual analysis unreliable.
 */
export function stripCypherLiterals(query: string): string {
  let out = ''
  let i = 0
  while (i < query.length) {
    const ch = query[i]!
    if (ch === "'" || ch === '"') {
      let j = i + 1
      let closed = false
      while (j < query.length) {
        if (query[j] === '\\') { j += 2; continue }
        if (query[j] === ch) { closed = true; break }
        j++
      }
      if (!closed) throw new UnsafeCypherError('string literal non terminato')
      out += ch + ch
      i = j + 1
      continue
    }
    if (ch === '/' && query[i + 1] === '/') {
      const nl = query.indexOf('\n', i)
      i = nl === -1 ? query.length : nl
      continue
    }
    if (ch === '/' && query[i + 1] === '*') {
      const end = query.indexOf('*/', i + 2)
      if (end === -1) throw new UnsafeCypherError('commento non terminato')
      out += ' '
      i = end + 2
      continue
    }
    if (ch === '\\') throw new UnsafeCypherError('backslash fuori da una stringa')
    if (ch === '`') throw new UnsafeCypherError('identificatori tra backtick non ammessi')
    if (ch === ';') throw new UnsafeCypherError('una sola istruzione per query (";" non ammesso)')
    out += ch
    i++
  }
  return out
}

function precedingToken(text: string, index: number): { word: string | null; char: string | null } {
  let k = index - 1
  while (k >= 0 && /\s/.test(text[k]!)) k--
  if (k < 0) return { word: null, char: null }
  const char = text[k]!
  if (!/[\w$]/.test(char)) return { word: null, char }
  let start = k
  while (start >= 0 && /[\w$]/.test(text[start]!)) start--
  return { word: text.slice(start + 1, k + 1), char }
}

interface NodePattern {
  alias:        string | null
  hasLabel:     boolean
  inlineTenant: boolean
  continues:    boolean   // preceded by `-` / `>` → same path as previous node
}

function extractNodePatterns(text: string): NodePattern[] {
  const nodes: NodePattern[] = []
  NODE_RE.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = NODE_RE.exec(text)) !== null) {
    const { word, char } = precedingToken(text, m.index)
    if (word !== null && !PATTERN_KEYWORDS.has(word.toUpperCase())) {
      // identifier( … ) → function call such as count(n), skip
      continue
    }
    nodes.push({
      alias:        m[1] ?? null,
      hasLabel:     (m[2] ?? '').length > 0,
      inlineTenant: m[3] ? INLINE_TENANT_RE.test(m[3]) : false,
      continues:    char === '-' || char === '>',
    })
  }
  return nodes
}

/**
 * Throws UnsafeCypherError unless `query` is a read-only, tenant-anchored
 * Cypher statement. Never mutates or executes anything.
 */
export function assertSafeReadOnlyCypher(query: string): void {
  if (typeof query !== 'string' || !query.trim()) throw new UnsafeCypherError('query vuota')
  if (query.length > MAX_CYPHER_LENGTH) throw new UnsafeCypherError(`query troppo lunga (> ${MAX_CYPHER_LENGTH} caratteri)`)

  const text = stripCypherLiterals(query)

  const write = WRITE_KEYWORD_RE.exec(text)
  if (write) throw new UnsafeCypherError(`clausola non ammessa: ${write[1]!.toUpperCase()} (sono consentite solo letture)`)
  if (DB_NAMESPACE_RE.test(text)) throw new UnsafeCypherError('procedure/funzioni db.* e dbms.* non ammesse')
  if (APOC_RE.test(text)) throw new UnsafeCypherError('apoc.* non ammesso (eccetto apoc.text/coll/map/date)')
  if (AUTH_RE.test(text)) throw new UnsafeCypherError('":auth" non ammesso')
  if (INLINE_WHERE_RE.test(text)) throw new UnsafeCypherError('WHERE dentro il pattern di nodo non supportato: usa {tenant_id: $tenantId}')

  CALL_RE.lastIndex = 0
  let call: RegExpExecArray | null
  while ((call = CALL_RE.exec(text)) !== null) {
    const target = call[1] ?? ''
    if (target.startsWith('{')) continue                 // CALL { subquery }
    if (SAFE_PROC_RE.test(target)) continue
    throw new UnsafeCypherError(`CALL ${target || '<procedura>'} non ammesso`)
  }

  PARAM_RE.lastIndex = 0
  let param: RegExpExecArray | null
  while ((param = PARAM_RE.exec(text)) !== null) {
    if (param[1] !== 'tenantId') throw new UnsafeCypherError(`parametro $${param[1]} non disponibile: l'unico parametro è $tenantId`)
  }

  // Aliases scoped via WHERE alias.tenant_id = $tenantId — only trusted when no
  // boolean operator could neutralise the predicate (… OR true, NOT (…)).
  const whereScoped = new Set<string>()
  WHERE_TENANT_RE.lastIndex = 0
  let ws: RegExpExecArray | null
  while ((ws = WHERE_TENANT_RE.exec(text)) !== null) whereScoped.add(ws[1] ?? ws[2]!)
  if (whereScoped.size > 0 && BOOLEAN_NEUTRALISER_RE.test(text.replace(IS_NOT_RE, 'IS_NOT'))) {
    throw new UnsafeCypherError('con OR/XOR/NOT nella query il vincolo tenant deve essere inline nel pattern: (x:Label {tenant_id: $tenantId})')
  }

  const nodes = extractNodePatterns(text)
  if (nodes.length === 0) throw new UnsafeCypherError('nessun pattern di nodo trovato: ogni query deve partire da MATCH (x:Label {tenant_id: $tenantId})')

  // Group into paths and require each one to be anchored.
  const paths: NodePattern[][] = []
  for (const n of nodes) {
    if (n.continues && paths.length) paths[paths.length - 1]!.push(n)
    else paths.push([n])
  }

  const bound = new Set<string>()
  for (const path of paths) {
    const anchored = path.some(n =>
      n.inlineTenant ||
      (n.alias !== null && (whereScoped.has(n.alias) || bound.has(n.alias))),
    )
    if (!anchored) {
      const first = path[0]!
      const desc = first.alias ?? (first.hasLabel ? '<senza alias>' : '()')
      throw new UnsafeCypherError(`pattern non vincolato al tenant a partire da (${desc}): aggiungi {tenant_id: $tenantId} nel nodo o ${first.alias ?? 'x'}.tenant_id = $tenantId`)
    }
    for (const n of path) if (n.alias) bound.add(n.alias)
  }
}
