// Conservative textual guard for Cypher generated by an LLM (reportAI).
//
// A system prompt is not a security boundary: the model (or an indirect prompt
// injection carried by ticket titles in tool results) can emit any query. Before
// execution we therefore require, textually and conservatively:
//
//   1. no write / admin / procedure clauses (CREATE, MERGE, SET, DELETE, CALL db.*,
//      apoc.* outside a small pure-function allowlist, LOAD CSV, dbms.*, ...);
//   2. no string-escaping tricks (backslashes, backticks, `;`, comments are stripped);
//   3. the only parameter is $tenantId;
//   4. EVERY path pattern is anchored to the tenant: at least one node of the path
//      carries `{tenant_id: $tenantId}` inline, or `alias.tenant_id = $tenantId`
//      in a WHERE (accepted only when the query has no OR/XOR/NOT that could
//      neutralise it), or re-uses an alias already bound by an anchored path.
//
//   5. what the tenant's graph holds but a report must never read (revisione
//      totale · D-1): every node pattern names its labels (or re-uses an alias
//      that does), no label is one of SENSITIVE_LABELS, no `!`/`%` label
//      expression, no access to a SENSITIVE_PROPERTY_KEYS property and no dynamic
//      `x['…']` access. Before, an operator with `report.ai` (or a prompt
//      injection in a ticket title) could read OutboundWebhook.secret/headers,
//      Slack webhook URLs and transform scripts through the tool.
//      `redactSensitiveValue` is the second line on the rows the query returns.
//
//   6. names are scoped as Cypher scopes them (review of 23 Sep 2026): after
//      WITH only the names it projects keep their anchor, the two sides of a
//      UNION share nothing, and a CALL { } body sees only what its leading WITH
//      imports. Before, a name anchored anywhere counted everywhere, and
//      `MATCH (x:Incident {tenant_id: $tenantId}) WITH count(x) AS c
//      MATCH (x:User) RETURN x.email` read the users of every tenant.
//      `foreignTenantIn` is the second line on the rows the query returns.
//
// The check is deliberately strict: a legitimate query it rejects costs the
// model one retry; a malicious query it accepts costs a cross-tenant leak.

export class UnsafeCypherError extends Error {
  readonly code = 'UNSAFE_CYPHER'
  constructor(message: string) {
    super(`Query rejected by the security guard: ${message}`)
    this.name = 'UnsafeCypherError'
  }
}

export const MAX_CYPHER_LENGTH = 4000

/**
 * Nodes holding integration secrets, credentials or configuration code: never readable by a report.
 *
 * I REGISTRI NON SONO DATI DI DOMINIO (20 set 2026, ondata 3).
 *
 * `AuditEntry`, `LogEntry` e `ServerLogEntry` sono entrati qui perché un
 * report non deve poterli leggere. Non contengono ticket: contengono il
 * RACCONTO di tutto quello che è successo, con i parametri delle mutation
 * (`auditableArgs()` oscura per NOME di chiave, quindi `url` e `headers` di
 * un webhook passano) e, nei log, il payload libero di chi ha scritto la
 * riga. Un operatore con `report.ai` poteva già chiederli oggi — buco
 * preesistente, trovato rileggendo il progetto. Si chiude PRIMA di
 * persistere i log del server, non dopo.
 */
export const SENSITIVE_LABELS: ReadonlySet<string> = new Set([
  'OutboundWebhook', 'InboundWebhook', 'ApiKey', 'NotificationChannel', 'SlackInstallation',
  'SyncSource', 'SyncConflict', 'SyncChangeRecord', 'MigrationLock', 'Migration', 'LoginProvider',
  'AuditEntry', 'LogEntry', 'ServerLogEntry',
])

/** Property names that hold secrets on any node. */
export const SENSITIVE_PROPERTY_KEYS: ReadonlySet<string> = new Set([
  'secret', 'headers', 'key_hash', 'key_prefix', 'webhook_url', 'transform_script', 'token', 'password',
  'credentials', 'encrypted_credentials', 'signing_secret', 'signing_secret_enc', 'bot_token', 'bot_token_enc',
  'client_secret', 'embedding',
  // Il corpo libero di una voce di registro: `AuditEntry.details` e
  // `LogEntry.data` sono JSON scritto da chi ha generato l'evento, e nessuno
  // ne ha mai promesso il contenuto. Vietati per nome anche fuori dai nodi
  // di sopra, perché la stessa chiave può ricomparire altrove.
  'details', 'data',
])

const WRITE_KEYWORD_RE = /(?<![\w.$])(CREATE|MERGE|SET|DELETE|DETACH|REMOVE|DROP|FOREACH|LOAD|USING|ALTER|GRANT|DENY|REVOKE|START|STOP|TERMINATE|INSTALL|IMPORT|EXPORT|SHOW|USE|ENABLE|RENAME|DEALLOCATE|ASSIGN|PERIODIC|COMMIT)(?!\w)/i
const CALL_RE          = /(?<![\w.])CALL(?!\w)\s*([^\s]*)/gi
const SAFE_PROC_RE     = /^apoc\.(text|coll|map|date)\.[A-Za-z0-9_.]+/
const DB_NAMESPACE_RE  = /(?<![\w.])(dbms|db)\./i
const APOC_RE          = /(?<![\w.])apoc\.(?!(text|coll|map|date)\.)/i
const AUTH_RE          = /:auth/i
const PARAM_RE         = /\$([A-Za-z_][A-Za-z0-9_]*)/g
const INLINE_WHERE_RE  = /\(\s*[A-Za-z_]?\w*\s*:\s*\w+[^()]*(?<!\w)WHERE(?!\w)/i

// (alias?)(:Label(:|&|| Label)*)?({inline map})?
const NODE_RE = /\(\s*([A-Za-z_][A-Za-z0-9_]*)?\s*((?::\s*[A-Za-z_][A-Za-z0-9_]*(?:\s*[:|&!]\s*[A-Za-z_][A-Za-z0-9_]*)*)?)\s*(\{[^{}]*\})?\s*\)/g
const INLINE_TENANT_RE = /(?<!\w)tenant_id\s*:\s*\$tenantId(?!\w)/
const WHERE_TENANT_RE  = /(?<![\w.])([A-Za-z_][A-Za-z0-9_]*)\.tenant_id\s*=\s*\$tenantId(?!\w)|\$tenantId\s*=\s*(?<![\w.])([A-Za-z_][A-Za-z0-9_]*)\.tenant_id(?!\w)/g
const BOOLEAN_NEUTRALISER_RE = /(?<![\w.])(OR|XOR|NOT)(?!\w)/i
const IS_NOT_RE = /(?<![\w.])IS\s+NOT(?!\w)/gi

const SENSITIVE_PROPERTY_RE = new RegExp(`(?<![\\w$])[A-Za-z_][A-Za-z0-9_]*\\s*\\.\\s*(${[...SENSITIVE_PROPERTY_KEYS].join('|')})(?!\\w)|\\{[^}]*(?<![\\w$])(${[...SENSITIVE_PROPERTY_KEYS].join('|')})\\s*:`, 'i')

/**
 * Seconda linea di D-1 sulle righe restituite: un nodo con un'etichetta
 * sensibile diventa `"[redacted]"`, una chiave sensibile di una mappa o di un
 * nodo sparisce. Ricorsiva su liste e mappe; i valori primitivi passano.
 */
export function redactSensitiveValue(value: unknown): unknown {
  if (value === null || typeof value !== 'object') return value
  if (Array.isArray(value)) return value.map(redactSensitiveValue)
  const v = value as Record<string, unknown>
  if (Array.isArray(v['labels']) && typeof v['properties'] === 'object' && v['properties'] !== null) {
    if ((v['labels'] as unknown[]).some((l) => typeof l === 'string' && SENSITIVE_LABELS.has(l))) return '[redacted]'
    return { ...v, properties: redactSensitiveValue(v['properties']) }
  }
  if ('toNumber' in v && typeof v['toNumber'] === 'function') return value
  const out: Record<string, unknown> = {}
  for (const [k, inner] of Object.entries(v)) {
    if (SENSITIVE_PROPERTY_KEYS.has(k.toLowerCase())) continue
    out[k] = redactSensitiveValue(inner)
  }
  return out
}

/** Words after which a `(` opens a pattern, not a function call. */
const PATTERN_KEYWORDS = new Set([
  'MATCH', 'WHERE', 'WITH', 'RETURN', 'AND', 'OR', 'XOR', 'NOT', 'UNWIND',
  'EXISTS', 'ALL', 'ANY', 'NONE', 'SINGLE', 'WHEN', 'THEN', 'ELSE', 'CASE',
  'END', 'IN', 'IS', 'OPTIONAL', 'CALL', 'YIELD', 'ON', 'STARTS', 'ENDS', 'CONTAINS',
  'UNION', 'DISTINCT', 'AS', 'BY', 'SKIP', 'LIMIT', 'ASC', 'DESC',
])

/**
 * Returns the query with string literal contents blanked ('' / "") and
 * comments removed. Throws on constructs that make textual analysis unreliable.
 */
export function stripCypherLiterals(query: string): string {
  let out = ''
  let i = 0
  while (i < query.length) {
    const ch = query[i]!
    if (ch === "'" || ch === '"') {
      let j = i + 1
      let closed = false
      while (j < query.length) {
        if (query[j] === '\\') { j += 2; continue }
        if (query[j] === ch) { closed = true; break }
        j++
      }
      if (!closed) throw new UnsafeCypherError('unterminated string literal')
      out += ch + ch
      i = j + 1
      continue
    }
    if (ch === '/' && query[i + 1] === '/') {
      const nl = query.indexOf('\n', i)
      i = nl === -1 ? query.length : nl
      continue
    }
    if (ch === '/' && query[i + 1] === '*') {
      const end = query.indexOf('*/', i + 2)
      if (end === -1) throw new UnsafeCypherError('unterminated comment')
      out += ' '
      i = end + 2
      continue
    }
    if (ch === '\\') throw new UnsafeCypherError('backslash outside a string')
    if (ch === '`') throw new UnsafeCypherError('backtick identifiers are not allowed')
    if (ch === ';') throw new UnsafeCypherError('one statement per query (";" is not allowed)')
    out += ch
    i++
  }
  return out
}

function precedingToken(text: string, index: number): { word: string | null; char: string | null } {
  let k = index - 1
  while (k >= 0 && /\s/.test(text[k]!)) k--
  if (k < 0) return { word: null, char: null }
  const char = text[k]!
  if (!/[\w$]/.test(char)) return { word: null, char }
  let start = k
  while (start >= 0 && /[\w$]/.test(text[start]!)) start--
  return { word: text.slice(start + 1, k + 1), char }
}

interface NodePattern {
  index:        number
  alias:        string | null
  hasLabel:     boolean
  labels:       string[]
  labelExpr:    string
  inlineTenant: boolean
  continues:    boolean   // preceded by `-` / `>` → same path as previous node
}

function extractNodePatterns(text: string): NodePattern[] {
  const nodes: NodePattern[] = []
  NODE_RE.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = NODE_RE.exec(text)) !== null) {
    const { word, char } = precedingToken(text, m.index)
    if (word !== null && !PATTERN_KEYWORDS.has(word.toUpperCase())) {
      // identifier( … ) → function call such as count(n), skip
      continue
    }
    nodes.push({
      index:        m.index,
      alias:        m[1] ?? null,
      hasLabel:     (m[2] ?? '').length > 0,
      labels:       (m[2] ?? '').split(/[:|&!%\s]+/).filter(Boolean),
      labelExpr:    m[2] ?? '',
      inlineTenant: m[3] ? INLINE_TENANT_RE.test(m[3]) : false,
      continues:    char === '-' || char === '>',
    })
  }
  return nodes
}

/**
 * Throws UnsafeCypherError unless `query` is a read-only, tenant-anchored
 * Cypher statement. Never mutates or executes anything.
 */
export function assertSafeReadOnlyCypher(query: string): void {
  if (typeof query !== 'string' || !query.trim()) throw new UnsafeCypherError('empty query')
  if (query.length > MAX_CYPHER_LENGTH) throw new UnsafeCypherError(`query too long (> ${MAX_CYPHER_LENGTH} characters)`)

  const text = stripCypherLiterals(query)

  const write = WRITE_KEYWORD_RE.exec(text)
  if (write) throw new UnsafeCypherError(`clause not allowed: ${write[1]!.toUpperCase()} (only reads are allowed)`)
  if (DB_NAMESPACE_RE.test(text)) throw new UnsafeCypherError('db.* and dbms.* procedures/functions are not allowed')
  if (APOC_RE.test(text)) throw new UnsafeCypherError('apoc.* is not allowed (except apoc.text/coll/map/date)')
  if (AUTH_RE.test(text)) throw new UnsafeCypherError('":auth" is not allowed')
  if (INLINE_WHERE_RE.test(text)) throw new UnsafeCypherError('WHERE inside a node pattern is not supported: use {tenant_id: $tenantId}')

  CALL_RE.lastIndex = 0
  let call: RegExpExecArray | null
  while ((call = CALL_RE.exec(text)) !== null) {
    const target = call[1] ?? ''
    if (target.startsWith('{')) continue                 // CALL { subquery }
    if (SAFE_PROC_RE.test(target)) continue
    throw new UnsafeCypherError(`CALL ${target || '<procedure>'} is not allowed`)
  }

  PARAM_RE.lastIndex = 0
  let param: RegExpExecArray | null
  while ((param = PARAM_RE.exec(text)) !== null) {
    if (param[1] !== 'tenantId') throw new UnsafeCypherError(`parameter $${param[1]} is not available: the only parameter is $tenantId`)
  }

  // Aliases scoped via WHERE alias.tenant_id = $tenantId — only trusted when no
  // boolean operator could neutralise the predicate (… OR true, NOT (…)).
  const whereScoped = new Set<string>()
  WHERE_TENANT_RE.lastIndex = 0
  let ws: RegExpExecArray | null
  while ((ws = WHERE_TENANT_RE.exec(text)) !== null) whereScoped.add(ws[1] ?? ws[2]!)
  if (whereScoped.size > 0 && BOOLEAN_NEUTRALISER_RE.test(text.replace(IS_NOT_RE, 'IS_NOT'))) {
    throw new UnsafeCypherError('with OR/XOR/NOT in the query the tenant constraint must be inline in the pattern: (x:Label {tenant_id: $tenantId})')
  }

  const nodes = extractNodePatterns(text)
  if (nodes.length === 0) throw new UnsafeCypherError('no node pattern found: every query must start from MATCH (x:Label {tenant_id: $tenantId})')

  // 4 and 6. Every path anchored to the tenant, name by name, scope by scope.
  assertScopedQuery(text, new Set())

  // 5. What a report must never read (D-1).
  for (const n of nodes) {
    if (/[!%]/.test(n.labelExpr)) throw new UnsafeCypherError('label expressions with ! or % are not allowed: name the labels')
    const denied = n.labels.find((l) => SENSITIVE_LABELS.has(l))
    if (denied) throw new UnsafeCypherError(`label ${denied} is not readable by reports`)
  }
  SENSITIVE_PROPERTY_RE.lastIndex = 0
  const prop = SENSITIVE_PROPERTY_RE.exec(text)
  if (prop) throw new UnsafeCypherError(`property ${prop[1]} is not readable by reports`)
  if (hasDynamicAccess(text)) throw new UnsafeCypherError('dynamic property access x[\'…\'] is not allowed: use x.property')

}

// ── Scopes (review of 23 Sep 2026) ─────────────────────────────────────────
//
// A name keeps its tenant anchor only inside the scope that bound it. The
// analysis runs on the text `stripCypherLiterals` returns, so brackets inside
// strings are already gone.

/** Words that end the projection of a WITH. */
const PROJECTION_END = new Set(['MATCH', 'OPTIONAL', 'WHERE', 'UNWIND', 'RETURN', 'ORDER', 'SKIP', 'LIMIT', 'CALL', 'WITH'])
/** Clause words a tenant predicate in a WHERE can be attached to. */
const CLAUSE_WORDS = new Set(['MATCH', 'OPTIONAL', 'WITH', 'UNWIND', 'RETURN', 'ORDER', 'CALL'])

interface Word { word: string; index: number; depth: number }

/** Nesting depth of every character: (), [] and {}. A closing bracket has the outer depth. */
function depthMap(text: string): number[] {
  const depth: number[] = new Array<number>(text.length)
  let d = 0
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!
    if (ch === ')' || ch === ']' || ch === '}') d = Math.max(0, d - 1)
    depth[i] = d
    if (ch === '(' || ch === '[' || ch === '{') d++
  }
  return depth
}

/** The bare words of the text, without property names, parameters and labels. */
function wordsOf(text: string, depth: number[]): Word[] {
  const out: Word[] = []
  const re = /[A-Za-z_][A-Za-z0-9_]*/g
  let m: RegExpExecArray | null
  while ((m = re.exec(text)) !== null) {
    const before = text.slice(0, m.index).trimEnd().slice(-1)
    if (before === '.' || before === ':' || text[m.index - 1] === '$') continue
    out.push({ word: m[0].toUpperCase(), index: m.index, depth: depth[m.index]! })
  }
  return out
}

/** Index of the bracket that closes the one at `open`. */
function closingOf(text: string, open: number): number {
  let d = 0
  for (let i = open; i < text.length; i++) {
    const ch = text[i]!
    if (ch === '(' || ch === '[' || ch === '{') d++
    else if (ch === ')' || ch === ']' || ch === '}') { d--; if (d === 0) return i }
  }
  throw new UnsafeCypherError('unbalanced brackets')
}

/** The query split at its top-level UNIONs: each side is a scope of its own. */
function unionParts(text: string): string[] {
  const depth = depthMap(text)
  const parts: string[] = []
  let start = 0
  for (const w of wordsOf(text, depth)) {
    if (w.word !== 'UNION') continue
    if (w.depth > 0) throw new UnsafeCypherError('UNION inside a subquery expression is not supported')
    parts.push(text.slice(start, w.index))
    start = w.index + 'UNION'.length
  }
  parts.push(text.slice(start))
  return parts.map((p) => p.replace(/^\s*ALL(?!\w)/i, ' '))
}

interface CallBody { start: number; body: string }

/** The top-level `CALL { … }` bodies, and the text with them blanked out. */
function callBodies(text: string): { outer: string; calls: CallBody[] } {
  const depth = depthMap(text)
  const calls: CallBody[] = []
  let outer = text
  let skipUntil = -1
  for (const w of wordsOf(text, depth)) {
    if (w.index < skipUntil || w.word !== 'CALL') continue
    const open = w.index + 4 + (text.slice(w.index + 4).search(/\S/))
    if (text[open] !== '{') continue   // a procedure: checked by CALL_RE
    if (w.depth > 0) throw new UnsafeCypherError('CALL { } is only supported at the top level of the query')
    const close = closingOf(text, open)
    calls.push({ start: w.index, body: text.slice(open + 1, close) })
    outer = outer.slice(0, w.index) + ' '.repeat(close + 1 - w.index) + outer.slice(close + 1)
    skipUntil = close + 1
  }
  return { outer, calls }
}

/** The names a WITH projection carries into the next scope with their anchor. */
function projectedNames(projection: string, anchored: ReadonlySet<string>): Set<string> {
  const out = new Set<string>()
  const depth = depthMap(projection)
  let start = 0
  const items: string[] = []
  for (let i = 0; i <= projection.length; i++) {
    if (i === projection.length || (projection[i] === ',' && depth[i] === 0)) { items.push(projection.slice(start, i)); start = i + 1 }
  }
  for (const raw of items) {
    const item = raw.trim().replace(/^DISTINCT(?!\w)\s*/i, '')
    if (item === '*') { for (const a of anchored) out.add(a); continue }
    const m = /^([A-Za-z_]\w*)(?:\s+AS\s+([A-Za-z_]\w*))?$/i.exec(item)
    if (m && anchored.has(m[1]!)) out.add(m[2] ?? m[1]!)
  }
  return out
}

/**
 * Aliases a `WHERE alias.tenant_id = $tenantId` really restricts: the WHERE
 * is at the top level of its scope and belongs to a MATCH (not an OPTIONAL
 * MATCH, whose WHERE only empties the optional part) or to a WITH.
 */
function whereAnchoredAliases(text: string, words: Word[], depth: number[], from: number, to: number, startsWithWith: boolean): Set<string> {
  const out = new Set<string>()
  WHERE_TENANT_RE.lastIndex = 0
  let m: RegExpExecArray | null
  while ((m = WHERE_TENANT_RE.exec(text)) !== null) {
    if (m.index < from || m.index >= to || depth[m.index] !== 0) continue
    const before = words.filter((w) => w.depth === 0 && w.index >= from && w.index < m!.index)
    const clause = [...before].reverse().find((w) => CLAUSE_WORDS.has(w.word))
    const inWhere = before.some((w) => w.word === 'WHERE' && (!clause || w.index > clause.index))
    if (!inWhere) continue
    const plainMatch = clause?.word === 'MATCH' && before[before.indexOf(clause) - 1]?.word !== 'OPTIONAL'
    if (plainMatch || clause?.word === 'WITH' || (!clause && startsWithWith)) out.add(m[1] ?? m[2]!)
  }
  return out
}

/** Throws unless every node pattern of the query is anchored to the tenant in its own scope. */
function assertScopedQuery(text: string, carried: ReadonlySet<string>): void {
  for (const part of unionParts(text)) assertScopedPart(part, carried)
}

function assertScopedPart(text: string, carried: ReadonlySet<string>): void {
  const { outer, calls } = callBodies(text)
  const depth = depthMap(outer)
  const words = wordsOf(outer, depth)
  const withs = words.filter((w, i) => w.word === 'WITH' && !['STARTS', 'ENDS'].includes(words[i - 1]?.word ?? ''))
  if (withs.some((w) => w.depth > 0)) throw new UnsafeCypherError('WITH inside a subquery expression is not supported')
  const nodes = extractNodePatterns(outer)

  let inScope = new Set(carried)
  const bounds = [0, ...withs.map((w) => w.index), outer.length]
  for (let k = 0; k < bounds.length - 1; k++) {
    const from = k === 0 ? 0 : bounds[k]! + 'WITH'.length
    const to = bounds[k + 1]!
    if (k > 0) {
      const end = words.find((w) => w.index >= from && w.index < to && w.depth === 0 && PROJECTION_END.has(w.word))?.index ?? to
      inScope = projectedNames(outer.slice(from, end), inScope)
    }
    const whereAnchored = whereAnchoredAliases(outer, words, depth, from, to, k > 0)
    const segmentNodes = nodes.filter((n) => n.index >= from && n.index < to)
    const segmentCalls = calls.filter((c) => c.start >= from && c.start < to)
    inScope = assertScopedSegment(segmentNodes, segmentCalls, inScope, whereAnchored)
  }
}

/** One scope: its paths in textual order, and the CALL bodies it contains. Returns the anchored names. */
function assertScopedSegment(nodes: NodePattern[], calls: CallBody[], inScope: ReadonlySet<string>, whereAnchored: ReadonlySet<string>): Set<string> {
  const anchored = new Set(inScope)
  const labeled = new Set<string>()
  const pending = [...calls]
  const paths: NodePattern[][] = []
  for (const n of nodes) {
    if (n.continues && paths.length) paths[paths.length - 1]!.push(n)
    else paths.push([n])
  }
  const runCallsBefore = (index: number) => {
    while (pending.length && pending[0]!.start < index) {
      const call = pending.shift()!
      const imports = /^\s*WITH(?!\w)/i.test(call.body) ? anchored : new Set<string>()
      assertScopedQuery(call.body, imports)
    }
  }
  for (const path of paths) {
    runCallsBefore(path[0]!.index)
    const ok = path.some((n) => n.inlineTenant || (n.alias !== null && (anchored.has(n.alias) || whereAnchored.has(n.alias))))
    if (!ok) {
      const first = path[0]!
      const desc = first.alias ?? (first.hasLabel ? '<no alias>' : '()')
      throw new UnsafeCypherError(`pattern not bound to the tenant starting from (${desc}): add {tenant_id: $tenantId} to the node or ${first.alias ?? 'x'}.tenant_id = $tenantId`)
    }
    for (const n of path) {
      if (!n.hasLabel && !(n.alias && (inScope.has(n.alias) || labeled.has(n.alias)))) {
        throw new UnsafeCypherError(`every node needs a label: (${n.alias ?? ''}) has none — write (${n.alias ?? 'x'}:Label)`)
      }
      if (n.alias) { anchored.add(n.alias); if (n.hasLabel) labeled.add(n.alias) }
    }
  }
  runCallsBefore(Number.POSITIVE_INFINITY)
  return anchored
}

/**
 * `x[k]` reads a property whose name the query computes, which the name checks
 * cannot see. A list read by a literal position or slice (`xs[0]`, `xs[..3]`)
 * is allowed, and so is a list literal after a keyword (`RETURN [a, b]`).
 */
function hasDynamicAccess(text: string): boolean {
  const re = /([A-Za-z0-9_)\]])\s*\[\s*(\S)/g
  let m: RegExpExecArray | null
  while ((m = re.exec(text)) !== null) {
    if (/[A-Za-z0-9_]/.test(m[1]!)) {
      const word = /[A-Za-z_][A-Za-z0-9_]*$/.exec(text.slice(0, m.index + 1))?.[0] ?? ''
      if (PATTERN_KEYWORDS.has(word.toUpperCase())) continue
    }
    if (/[0-9.-]/.test(m[2]!)) continue
    return true
  }
  return false
}

/**
 * Second line behind the guard (review of 23 Sep 2026): true when a node the
 * query returned belongs to another tenant. Shared shipped nodes
 * (`tenant_id = 'system'`) are not another tenant.
 */
export function foreignTenantIn(value: unknown, tenantId: string): boolean {
  if (value === null || typeof value !== 'object') return false
  if (Array.isArray(value)) return value.some((v) => foreignTenantIn(v, tenantId))
  const v = value as Record<string, unknown>
  if ('toNumber' in v && typeof v['toNumber'] === 'function') return false
  if (Array.isArray(v['labels']) && typeof v['properties'] === 'object' && v['properties'] !== null) {
    const owner = (v['properties'] as Record<string, unknown>)['tenant_id']
    if (typeof owner === 'string' && owner !== tenantId && owner !== 'system') return true
  }
  return Object.values(v).some((inner) => foreignTenantIn(inner, tenantId))
}
