import { ValidationError } from './errors.js'
import {
  LABEL_RE, REL_TYPE_RE,
  assertFieldName, assertSortDir,
} from './cypherIdentifiers.js'
import type { ReportWhitelist } from './reportWhitelist.js'

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ReportNodeDef {
  id:             string
  entityType:     string
  neo4jLabel:     string
  label:          string
  isResult:       boolean
  isRoot:         boolean
  positionX:      number
  positionY:      number
  filters:        string | null
  selectedFields: string[]
}

export interface ReportEdgeDef {
  id:               string
  sourceNodeId:     string
  targetNodeId:     string
  relationshipType: string
  direction:        string
  label:            string
}

export interface ReportSectionDef {
  id:            string
  order:         number
  title:         string
  chartType:     string
  groupByNodeId: string | null
  groupByField:  string | null
  metric:        string
  metricField:   string | null
  limit:         number | null
  sortDir:       string | null
  nodes:         ReportNodeDef[]
  edges:         ReportEdgeDef[]
}

interface FilterClause {
  field:    string
  operator: string
  value:    unknown
}

/** Table column: Cypher alias generated by the builder + display name for the UI. */
export interface ReportColumn {
  alias: string
  name:  string
}

export interface BuiltReportQuery {
  query:   string
  params:  Record<string, unknown>
  columns: ReportColumn[]
}

export const CHART_TYPES = ['kpi', 'pie', 'donut', 'bar', 'bar_horizontal', 'line', 'area', 'table', 'top_n'] as const
export const FILTER_OPERATORS = ['eq', 'neq', 'contains', 'in', 'last_n_days', 'is_null', 'is_not_null'] as const
export const EDGE_DIRECTIONS = ['outgoing', 'incoming'] as const
export const MAX_REPORT_LIMIT = 1000

// ── Helpers ───────────────────────────────────────────────────────────────────

function toSnakeCase(s: string): string {
  return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '')
}

/** Display name of a table column (UI-facing; never interpolated into Cypher). */
export function tableColumnName(node: ReportNodeDef, field: string): string {
  return `${node.label.replace(/\s+/g, '_')}_${field}`
}

function parseFilters(filtersJson: string | null, what: string): FilterClause[] {
  if (!filtersJson) return []
  let clauses: unknown
  try { clauses = JSON.parse(filtersJson) }
  catch (e) {
    // Corrupt section filters must fail the report — returning [] would render
    // an UNFILTERED report the user believes is filtered.
    throw new ValidationError(`${what}: invalid filters JSON: ${e instanceof Error ? e.message : String(e)}`)
  }
  if (!Array.isArray(clauses)) throw new ValidationError(`${what}: filters must be a JSON array`)
  return clauses.map((c, i) => {
    if (!c || typeof c !== 'object') throw new ValidationError(`${what}: filter #${i} must be an object`)
    const f = c as Partial<FilterClause>
    const field = assertFieldName(toSnakeCase(String(f.field ?? '')), `${what}: filter #${i} field`)
    if (!(FILTER_OPERATORS as readonly string[]).includes(String(f.operator))) {
      throw new ValidationError(`${what}: filter #${i} unknown operator ${JSON.stringify(f.operator)}`)
    }
    return { field, operator: f.operator as string, value: f.value }
  })
}

function buildWhereClause(
  nodeVar: string,
  clauses: FilterClause[],
  params: Record<string, unknown>,
  paramPrefix: string,
): string {
  if (!clauses.length) return ''

  const parts: string[] = []
  clauses.forEach((f, i) => {
    // Field names were validated by parseFilters; re-check so this function can
    // never emit an unvalidated identifier even if called from elsewhere.
    const field    = assertFieldName(f.field, `filter #${i} field`)
    const paramKey = `${paramPrefix}_f${i}`
    switch (f.operator) {
      case 'eq':
        params[paramKey] = f.value
        parts.push(`${nodeVar}.${field} = $${paramKey}`)
        break
      case 'neq':
        params[paramKey] = f.value
        parts.push(`${nodeVar}.${field} <> $${paramKey}`)
        break
      case 'contains':
        params[paramKey] = String(f.value)
        parts.push(`toLower(${nodeVar}.${field}) CONTAINS toLower($${paramKey})`)
        break
      case 'in':
        params[paramKey] = f.value
        parts.push(`${nodeVar}.${field} IN $${paramKey}`)
        break
      case 'last_n_days':
        params[paramKey] = Number(f.value)
        parts.push(`${nodeVar}.${field} > datetime() - duration({days: $${paramKey}})`)
        break
      case 'is_null':
        parts.push(`${nodeVar}.${field} IS NULL`)
        break
      case 'is_not_null':
        parts.push(`${nodeVar}.${field} IS NOT NULL`)
        break
      default:
        // Unknown operator = corrupt/stale section config — refuse, don't drop.
        throw new ValidationError(`Unknown report filter operator: ${JSON.stringify(f.operator)}`)
    }
  })
  return `WHERE ${parts.join(' AND ')}`
}

// ── Validation (build time AND persistence time) ──────────────────────────────

/**
 * Validates every identifier a section would interpolate into Cypher against
 * the tenant whitelist / identifier regexes. Throws ValidationError.
 *
 * Called by buildReportQuery (so scheduler/dashboard/export are covered even
 * for sections persisted before this check existed) and by the section
 * mutations (so a malicious section is never stored in the first place).
 */
export function validateReportSection(section: ReportSectionDef, whitelist: ReportWhitelist): void {
  const where = `section ${JSON.stringify(section.id)}`

  if (!(CHART_TYPES as readonly string[]).includes(section.chartType)) {
    throw new ValidationError(`${where}: unsupported chartType ${JSON.stringify(section.chartType)}`)
  }
  if (section.limit != null) {
    if (!Number.isInteger(section.limit) || section.limit < 1 || section.limit > MAX_REPORT_LIMIT) {
      throw new ValidationError(`${where}: limit must be an integer between 1 and ${MAX_REPORT_LIMIT}`)
    }
  }
  if (section.sortDir != null) assertSortDir(section.sortDir, `${where}: sortDir`)
  if (section.groupByField != null) assertFieldName(toSnakeCase(section.groupByField), `${where}: groupByField`)
  if (section.metricField != null) assertFieldName(toSnakeCase(section.metricField), `${where}: metricField`)

  if (!Array.isArray(section.nodes) || section.nodes.length === 0) {
    throw new ValidationError(`${where}: at least one node is required`)
  }
  const ids = new Set<string>()
  for (const n of section.nodes) {
    const nw = `${where}: node ${JSON.stringify(n.id)}`
    if (typeof n.id !== 'string' || !n.id) throw new ValidationError(`${where}: node id is required`)
    if (ids.has(n.id)) throw new ValidationError(`${nw}: duplicate node id`)
    ids.add(n.id)
    if (typeof n.neo4jLabel !== 'string' || !LABEL_RE.test(n.neo4jLabel) || !whitelist.labels.has(n.neo4jLabel)) {
      throw new ValidationError(`${nw}: neo4jLabel ${JSON.stringify(String(n.neo4jLabel).slice(0, 60))} is not a reportable entity`)
    }
    for (const sf of (n.selectedFields ?? [])) {
      assertFieldName(toSnakeCase(String(sf)), `${nw}: selectedFields`)
    }
    parseFilters(n.filters ?? null, nw)
  }

  const roots = section.nodes.filter(n => n.isRoot)
  if (roots.length !== 1) throw new ValidationError(`${where}: exactly one root node is required (found ${roots.length})`)

  if (section.groupByNodeId != null && !ids.has(section.groupByNodeId)) {
    throw new ValidationError(`${where}: groupByNodeId ${JSON.stringify(section.groupByNodeId)} does not match any section node — stale report config`)
  }

  for (const e of (section.edges ?? [])) {
    const ew = `${where}: edge ${JSON.stringify(e.id)}`
    if (!ids.has(e.sourceNodeId) || !ids.has(e.targetNodeId)) {
      throw new ValidationError(`${ew}: sourceNodeId/targetNodeId must reference section nodes`)
    }
    if (typeof e.relationshipType !== 'string' || !REL_TYPE_RE.test(e.relationshipType) || !whitelist.relationshipTypes.has(e.relationshipType)) {
      throw new ValidationError(`${ew}: relationshipType ${JSON.stringify(String(e.relationshipType).slice(0, 60))} is not a reportable relationship`)
    }
    if (!(EDGE_DIRECTIONS as readonly string[]).includes(e.direction)) {
      throw new ValidationError(`${ew}: direction must be one of ${EDGE_DIRECTIONS.join(', ')}`)
    }
  }
}

// ── Main export ───────────────────────────────────────────────────────────────

export function buildReportQuery(
  section: ReportSectionDef,
  tenantId: string,
  whitelist: ReportWhitelist,
): BuiltReportQuery {
  validateReportSection(section, whitelist)

  const params: Record<string, unknown> = { tenantId }
  const { nodes, edges, chartType, groupByNodeId, groupByField, limit, sortDir } = section

  // Cypher variables are generated by index — never derived from input ids.
  const varOf = new Map<string, string>(nodes.map((n, i) => [n.id, `n${i}`]))
  const v = (id: string): string => {
    const name = varOf.get(id)
    if (!name) throw new ValidationError(`Unknown node id ${JSON.stringify(id)}`)
    return name
  }

  // 1. Root node (validation guarantees exactly one)
  const rootNode = nodes.find(n => n.isRoot)!

  // 2. BFS to build match clauses in order
  const matchLines: string[] = []
  const visited = new Set<string>()
  const queue: string[] = [rootNode.id]

  const rootVar = v(rootNode.id)
  matchLines.push(`MATCH (${rootVar}:${rootNode.neo4jLabel} {tenant_id: $tenantId})`)
  const rootWhere = buildWhereClause(rootVar, parseFilters(rootNode.filters, 'root node'), params, rootVar)
  if (rootWhere) matchLines.push(rootWhere)
  visited.add(rootNode.id)

  const addChild = (parentId: string, childNode: ReportNodeDef, relType: string, outgoing: boolean) => {
    const parentVar = v(parentId)
    const childVar  = v(childNode.id)
    matchLines.push(outgoing
      ? `MATCH (${parentVar})-[:${relType}]->(${childVar}:${childNode.neo4jLabel})`
      : `MATCH (${parentVar})<-[:${relType}]-(${childVar}:${childNode.neo4jLabel})`)
    const childWhere = buildWhereClause(childVar, parseFilters(childNode.filters, `node ${childNode.id}`), params, childVar)
    if (childWhere) matchLines.push(childWhere)
    visited.add(childNode.id)
    queue.push(childNode.id)
  }

  while (queue.length) {
    const currentId = queue.shift()!
    const outEdges = edges.filter(e => e.sourceNodeId === currentId && !visited.has(e.targetNodeId))
    const inEdges  = edges.filter(e => e.targetNodeId === currentId && !visited.has(e.sourceNodeId))

    for (const edge of outEdges) {
      const childNode = nodes.find(n => n.id === edge.targetNodeId)
      if (!childNode || visited.has(childNode.id)) continue
      addChild(currentId, childNode, edge.relationshipType, edge.direction === 'outgoing')
    }

    for (const edge of inEdges) {
      const childNode = nodes.find(n => n.id === edge.sourceNodeId)
      if (!childNode || visited.has(childNode.id)) continue
      addChild(currentId, childNode, edge.relationshipType, edge.direction !== 'incoming')
    }
  }

  // 3. Group node (validation guarantees groupByNodeId, when set, exists)
  const groupNode  = groupByNodeId ? nodes.find(n => n.id === groupByNodeId)! : rootNode
  const groupVar   = v(groupNode.id)
  const groupField = groupByField ? assertFieldName(toSnakeCase(groupByField), 'groupByField') : null

  // 4. RETURN clause
  const limitVal   = limit ?? 20
  const sortDirVal = assertSortDir(sortDir ?? 'DESC', 'sortDir')
  params['limit']  = limitVal

  let returnClause = ''
  const columns: ReportColumn[] = []

  if (chartType === 'kpi') {
    returnClause = `RETURN count(${rootVar}) AS value`

  } else if (['pie', 'donut', 'bar', 'bar_horizontal'].includes(chartType)) {
    const field = groupField ?? 'status'
    returnClause = [
      `RETURN ${groupVar}.${field} AS label, count(${rootVar}) AS value`,
      `ORDER BY value ${sortDirVal}`,
      `LIMIT toInteger($limit)`,
    ].join('\n')

  } else if (['line', 'area'].includes(chartType)) {
    const field = groupField ?? 'created_at'
    returnClause = [
      `RETURN date(${groupVar}.${field}) AS label, count(${rootVar}) AS value`,
      `ORDER BY label ASC`,
    ].join('\n')

  } else if (chartType === 'table') {
    const cols: string[] = []
    for (const rn of nodes.filter(n => n.isResult)) {
      const rv = v(rn.id)
      for (const sf of (rn.selectedFields ?? [])) {
        const snakeSf = assertFieldName(toSnakeCase(sf), `node ${rn.id} selectedFields`)
        const alias   = `c${columns.length}`
        columns.push({ alias, name: tableColumnName(rn, sf) })
        cols.push(`${rv}.${snakeSf} AS ${alias}`)
      }
    }
    if (!cols.length) {
      columns.push({ alias: 'c0', name: 'id' })
      cols.push(`${rootVar}.id AS c0`)
    }
    returnClause = [
      `RETURN ${cols.join(', ')}`,
      `LIMIT toInteger($limit)`,
    ].join('\n')

  } else {
    returnClause = `RETURN count(${rootVar}) AS value`
  }

  const query = [...matchLines, returnClause].join('\n')
  return { query, params, columns }
}
