import { getSession, toNumber } from '@opengraphity/neo4j'
import { buildReportQuery, assertChartType, type ChartType, type ReportSectionDef } from './reportQueryBuilder.js'
import { getReportWhitelist } from './reportWhitelist.js'
import { reportFieldLabels } from './reportFieldLabels.js'
import { identityLabeler, loadReportValueLabeler, type ReportValueLabeler, type ReportValueSource } from './reportValueLabels.js'
import type { Lingua } from './enumValueLabels.js'

export interface ReportSectionResult {
  sectionId: string
  title:     string
  chartType: string
  data:      string  // JSON
  total:     number | null
  error:     string | null
  /** La chiave i18n, se l'errore è di quelli che l'utente può causare. */
  errorKey:  string | null
}

interface ExecutedData { data: unknown; total: number }

/**
 * Maps result rows to the JSON payload of a section. Exhaustive on ChartType:
 * the RETURN shape produced by buildReportQuery for each type is the contract
 * this function relies on (see the comment on CHART_TYPES).
 */
/**
 * L'ETICHETTA DI UN PUNTO DI UNA SERIE, che non diventi mai «[object Object]».
 *
 * Il Cypher la converte già in testo (`toString(date…)`), e questa è la rete:
 * se un giorno arrivasse di nuovo un oggetto temporale — una query scritta a
 * mano, un driver che cambia — una data va scritta come data invece di
 * lasciare all'utente la parola che l'asse ha mostrato per mesi.
 */
export function etichettaTemporale(raw: unknown): string {
  if (raw == null) return ''
  if (typeof raw === 'string') return raw
  if (typeof raw === 'object') {
    const o = raw as Record<string, unknown>
    const n = (v: unknown): number | null => {
      if (typeof v === 'number') return v
      if (typeof v === 'bigint') return Number(v)
      // I numeri «lossless» del driver: {low, high}.
      if (v !== null && typeof v === 'object' && 'low' in (v as object)) return Number((v as { low: number }).low)
      return null
    }
    const anno = n(o['year']), mese = n(o['month']), giorno = n(o['day'])
    if (anno !== null && mese !== null && giorno !== null) {
      const due = (x: number) => String(x).padStart(2, '0')
      return `${String(anno)}-${due(mese)}-${due(giorno)}`
    }
    // Un oggetto con un `toString` suo (il tipo del driver) lo sa fare da sé.
    const testo = String(raw)
    return testo === '[object Object]' ? JSON.stringify(raw) : testo
  }
  return String(raw)
}

export function mapSectionRecords(
  chartType: ChartType,
  section: Pick<ReportSectionDef, 'title'>,
  records: Array<{ get: (k: string) => unknown }>,
  columns: Array<{ alias: string; name: string; source?: ReportValueSource | null }>,
  labels: { group: ReportValueSource | null; labeler: ReportValueLabeler } = { group: null, labeler: identityLabeler },
): ExecutedData {
  switch (chartType) {
    case 'kpi': {
      // A Cypher aggregate always returns one row: zero records means the
      // query shape is wrong — error, don't render a fabricated 0.
      if (records.length === 0) {
        throw new Error('KPI query returned no rows — check the section configuration')
      }
      const v = toNumber(records[0]!.get('value'))
      return { data: { value: v, label: section.title }, total: v }
    }

    case 'pie':
    case 'donut':
    case 'bar':
    case 'bar_horizontal':
    case 'top_n': {
      const data = records.map(r => ({
        name:  labels.labeler(labels.group, r.get('label')) ?? '(none)',
        value: toNumber(r.get('value')),
      }))
      return { data, total: data.length }
    }

    case 'line':
    case 'area': {
      const data = records.map(r => ({
        date:  etichettaTemporale(r.get('label')),
        value: toNumber(r.get('value')),
      }))
      return { data, total: data.length }
    }

    case 'table': {
      // Column aliases (c0, c1, …) are generated by the builder; display
      // names come from the section config. A column missing from the
      // result is a config/query mismatch: let it throw into the section
      // error instead of rendering null cells the user cannot distinguish
      // from real empty values.
      const rows = records.map(r => columns.map(col => labels.labeler(col.source ?? null, r.get(col.alias)) ?? null))
      return { data: { columns: columns.map(c => c.name), rows }, total: records.length }
    }

    default: {
      const unhandled: never = chartType
      throw new Error(`Unhandled chartType ${JSON.stringify(unhandled)}`)
    }
  }
}

/** La chiave i18n dentro `extensions.i18n.key` di un errore GraphQL, se c'è. */
function chiaveI18n(err: unknown): string | null {
  const ext = (err as { extensions?: { i18n?: { key?: unknown } } } | null)?.extensions
  const key = ext?.i18n?.key
  return typeof key === 'string' ? key : null
}

export async function executeReportSection(
  section: ReportSectionDef,
  tenantId: string,
  /** La lingua di chi guarda, per le etichette dei valori (V-20); assente = quella del cliente. */
  opts: { language?: Lingua } = {},
): Promise<ReportSectionResult> {
  try {
    // Whitelist is tenant-scoped (metamodel CI types) — every execution path
    // (GraphQL, dashboard widgets, scheduler, export) goes through here, so a
    // section persisted with a rogue label/field never reaches Neo4j.
    const whitelist = await getReportWhitelist(tenantId)
    // Le etichette dei campi per le intestazioni delle colonne: dallo stesso
    // metamodello che il costruttore di report mostra all'amministratore, così
    // la colonna si chiama come la casella che ha spuntato.
    const fieldLabels = await reportFieldLabels(tenantId)
    const { query, params, columns, groupSource } = buildReportQuery(section, tenantId, whitelist, { fieldLabels })
    const chartType = assertChartType(section.chartType, `section ${JSON.stringify(section.id)}`)

    const session = getSession(undefined, 'READ')
    let executed: ExecutedData
    try {
      const result = await session.executeRead(tx => tx.run(query, params))
      const labeler = await loadReportValueLabeler(session, tenantId, [groupSource, ...columns.map(c => c.source)], opts.language)
      executed = mapSectionRecords(chartType, section, result.records, columns, { group: groupSource, labeler })
    } finally {
      await session.close()
    }

    return {
      sectionId: section.id,
      title:     section.title,
      chartType: section.chartType,
      data:      JSON.stringify(executed.data),
      total:     executed.total,
      error:     null,
      errorKey:  null,
    }
  } catch (err) {
    return {
      sectionId: section.id,
      title:     section.title,
      chartType: section.chartType,
      data:      '{}',
      total:     null,
      error:     err instanceof Error ? err.message : String(err),
      // La chiave viaggia con l'errore: il browser la traduce, e se non c'è
      // mostra il messaggio tecnico, che per un difetto nostro è il dato utile.
      errorKey:  chiaveI18n(err),
    }
  }
}
