import { getSession, toNumber } from '@opengraphity/neo4j'
import { buildReportQuery, assertChartType, type ChartType, type ReportSectionDef } from './reportQueryBuilder.js'
import { getReportWhitelist } from './reportWhitelist.js'
import { reportFieldLabels } from './reportFieldLabels.js'
import { identityLabeler, loadReportValueLabeler, type ReportValueLabeler, type ReportValueSource } from './reportValueLabels.js'
import type { Lingua } from './enumValueLabels.js'

export interface ReportSectionResult {
  sectionId: string
  title:     string
  chartType: string
  data:      string  // JSON
  total:     number | null
  error:     string | null
}

interface ExecutedData { data: unknown; total: number }

/**
 * Maps result rows to the JSON payload of a section. Exhaustive on ChartType:
 * the RETURN shape produced by buildReportQuery for each type is the contract
 * this function relies on (see the comment on CHART_TYPES).
 */
export function mapSectionRecords(
  chartType: ChartType,
  section: Pick<ReportSectionDef, 'title'>,
  records: Array<{ get: (k: string) => unknown }>,
  columns: Array<{ alias: string; name: string; source?: ReportValueSource | null }>,
  labels: { group: ReportValueSource | null; labeler: ReportValueLabeler } = { group: null, labeler: identityLabeler },
): ExecutedData {
  switch (chartType) {
    case 'kpi': {
      // A Cypher aggregate always returns one row: zero records means the
      // query shape is wrong — error, don't render a fabricated 0.
      if (records.length === 0) {
        throw new Error('KPI query returned no rows — check the section configuration')
      }
      const v = toNumber(records[0]!.get('value'))
      return { data: { value: v, label: section.title }, total: v }
    }

    case 'pie':
    case 'donut':
    case 'bar':
    case 'bar_horizontal':
    case 'top_n': {
      const data = records.map(r => ({
        name:  labels.labeler(labels.group, r.get('label')) ?? '(none)',
        value: toNumber(r.get('value')),
      }))
      return { data, total: data.length }
    }

    case 'line':
    case 'area': {
      const data = records.map(r => ({
        date:  String(r.get('label') ?? ''),
        value: toNumber(r.get('value')),
      }))
      return { data, total: data.length }
    }

    case 'table': {
      // Column aliases (c0, c1, …) are generated by the builder; display
      // names come from the section config. A column missing from the
      // result is a config/query mismatch: let it throw into the section
      // error instead of rendering null cells the user cannot distinguish
      // from real empty values.
      const rows = records.map(r => columns.map(col => labels.labeler(col.source ?? null, r.get(col.alias)) ?? null))
      return { data: { columns: columns.map(c => c.name), rows }, total: records.length }
    }

    default: {
      const unhandled: never = chartType
      throw new Error(`Unhandled chartType ${JSON.stringify(unhandled)}`)
    }
  }
}

export async function executeReportSection(
  section: ReportSectionDef,
  tenantId: string,
  /** La lingua di chi guarda, per le etichette dei valori (V-20); assente = quella del cliente. */
  opts: { language?: Lingua } = {},
): Promise<ReportSectionResult> {
  try {
    // Whitelist is tenant-scoped (metamodel CI types) — every execution path
    // (GraphQL, dashboard widgets, scheduler, export) goes through here, so a
    // section persisted with a rogue label/field never reaches Neo4j.
    const whitelist = await getReportWhitelist(tenantId)
    // Le etichette dei campi per le intestazioni delle colonne: dallo stesso
    // metamodello che il costruttore di report mostra all'amministratore, così
    // la colonna si chiama come la casella che ha spuntato.
    const fieldLabels = await reportFieldLabels(tenantId)
    const { query, params, columns, groupSource } = buildReportQuery(section, tenantId, whitelist, { fieldLabels })
    const chartType = assertChartType(section.chartType, `section ${JSON.stringify(section.id)}`)

    const session = getSession(undefined, 'READ')
    let executed: ExecutedData
    try {
      const result = await session.executeRead(tx => tx.run(query, params))
      const labeler = await loadReportValueLabeler(session, tenantId, [groupSource, ...columns.map(c => c.source)], opts.language)
      executed = mapSectionRecords(chartType, section, result.records, columns, { group: groupSource, labeler })
    } finally {
      await session.close()
    }

    return {
      sectionId: section.id,
      title:     section.title,
      chartType: section.chartType,
      data:      JSON.stringify(executed.data),
      total:     executed.total,
      error:     null,
    }
  } catch (err) {
    return {
      sectionId: section.id,
      title:     section.title,
      chartType: section.chartType,
      data:      '{}',
      total:     null,
      error:     err instanceof Error ? err.message : String(err),
    }
  }
}
