import { getSession } from '@opengraphity/neo4j'
import type { Integer } from 'neo4j-driver'
import { buildReportQuery, type ReportSectionDef } from './reportQueryBuilder.js'
import { getReportWhitelist } from './reportWhitelist.js'

export interface ReportSectionResult {
  sectionId: string
  title:     string
  chartType: string
  data:      string  // JSON
  total:     number | null
  error:     string | null
}

function toNumber(v: unknown): number {
  if (typeof v === 'number') return v
  if (v && typeof (v as Integer).toNumber === 'function') return (v as Integer).toNumber()
  return Number(v) || 0
}

export async function executeReportSection(
  section: ReportSectionDef,
  tenantId: string,
): Promise<ReportSectionResult> {
  try {
    // Whitelist is tenant-scoped (metamodel CI types) — every execution path
    // (GraphQL, dashboard widgets, scheduler, export) goes through here, so a
    // section persisted with a rogue label/field never reaches Neo4j.
    const whitelist = await getReportWhitelist(tenantId)
    const { query, params, columns } = buildReportQuery(section, tenantId, whitelist)

    const session = getSession(undefined, 'READ')
    let data: unknown
    let total: number | null = null

    try {
      const result = await session.executeRead(tx => tx.run(query, params))

      switch (section.chartType) {
        case 'kpi': {
          // A Cypher aggregate always returns one row: zero records means the
          // query shape is wrong — error, don't render a fabricated 0.
          if (result.records.length === 0) {
            throw new Error('KPI query returned no rows — check the section configuration')
          }
          const v = result.records[0]!.get('value')
          data = { value: toNumber(v), label: section.title }
          total = toNumber(v)
          break
        }

        case 'pie':
        case 'donut':
        case 'bar':
        case 'bar_horizontal':
        case 'top_n': {
          data = result.records.map(r => ({
            name:  r.get('label') ?? '(none)',
            value: toNumber(r.get('value')),
          }))
          total = (data as unknown[]).length
          break
        }

        case 'line':
        case 'area': {
          data = result.records.map(r => ({
            date:  String(r.get('label') ?? ''),
            value: toNumber(r.get('value')),
          }))
          total = (data as unknown[]).length
          break
        }

        case 'table': {
          // Column aliases (c0, c1, …) are generated by the builder; display
          // names come from the section config. A column missing from the
          // result is a config/query mismatch: let it throw into the section
          // error instead of rendering null cells the user cannot distinguish
          // from real empty values.
          const rows = result.records.map(r =>
            columns.map(col => r.get(col.alias) ?? null),
          )
          data = { columns: columns.map(c => c.name), rows }
          total = result.records.length
          break
        }

        default: {
          const v = result.records[0]?.get('value') ?? 0
          data = { value: toNumber(v) }
          total = toNumber(v)
        }
      }
    } finally {
      await session.close()
    }

    return {
      sectionId: section.id,
      title:     section.title,
      chartType: section.chartType,
      data:      JSON.stringify(data),
      total,
      error:     null,
    }
  } catch (err) {
    return {
      sectionId: section.id,
      title:     section.title,
      chartType: section.chartType,
      data:      '{}',
      total:     null,
      error:     err instanceof Error ? err.message : String(err),
    }
  }
}
