import {
  changes,
  change,
  changeAffectedCIs,
  changeAuditTrail,
  changeImpactedCIs,
  taskById,
  assessmentQuestionCatalog,
  assessmentQuestionsAdmin,
  questionCITypeAssignments,
  myTasks,
  changeResolvesIncidents,
  changeResolvesProblems,
} from './queries.js'
import {
  createChange,
  addCIToChange,
  removeCIFromChange,
  submitAssessmentResponse,
  completeAssessmentTask,
  assignAssessmentTaskToTeam,
  assignAssessmentTaskToUser,
  assignDeployPlanTaskToUser,
  saveDeployPlan,
  completeDeployPlanTask,
  executeChangeTransition,
  completeValidationTest,
  completeDeployment,
  completeReview,
  reopenAssessmentTask,
  reopenDeployPlanTask,
  reopenValidationTest,
  reopenDeploymentTask,
  reopenReviewTask,
  sendTaskReminder,
} from './mutations.js'
import {
  createAssessmentQuestion,
  updateAssessmentQuestion,
  deleteAssessmentQuestion,
  assignQuestionToCIType,
  removeQuestionFromCIType,
  setQuestionCore,
} from './questionAdmin.js'
import {
  approveChangeApproval,
  rejectChangeApproval,
  changeApprovals,
} from './approvalGate.js'

export const changeResolvers = {
  Query: {
    changes,
    change,
    changeAffectedCIs,
    changeAuditTrail,
    changeImpactedCIs,
    taskById,
    assessmentQuestionCatalog,
    assessmentQuestionsAdmin,
    questionCITypeAssignments,
    myTasks,
  },
  Mutation: {
    createChange,
    addCIToChange,
    removeCIFromChange,
    submitAssessmentResponse,
    completeAssessmentTask,
    assignAssessmentTaskToTeam,
    assignAssessmentTaskToUser,
    assignDeployPlanTaskToUser,
    saveDeployPlan,
    completeDeployPlanTask,
    executeChangeTransition,
    completeValidationTest,
    completeDeployment,
    completeReview,
    createAssessmentQuestion,
    updateAssessmentQuestion,
    deleteAssessmentQuestion,
    assignQuestionToCIType,
    removeQuestionFromCIType,
    setQuestionCore,
    reopenAssessmentTask,
    reopenDeployPlanTask,
    reopenValidationTest,
    reopenDeploymentTask,
    reopenReviewTask,
    sendTaskReminder,
    approveChangeApproval,
    rejectChangeApproval,
  },
  Change: {
    resolvesIncidents: changeResolvesIncidents,
    resolvesProblems:  changeResolvesProblems,
    approvals:         changeApprovals,
  },
}
